### PR TITLE
Fix curriculum form

### LINKED ISSUE #247: Curriculum form is not working
- Can't  remove a position that was added in the form from a experience

### PR DESCRIPTION
**Pull request by joaodiaslobo**
Fixes #247

### CODE REVIEW

**Comment by joaodiaslobo** [comment]
@RuiL1904 
> image 
>It's not possible to remove the first position entry.

Now you can remove the first position entry **but only if there are other positions left**.

File: lib/parzival/gamification/mission.ex [hunk 1]
```diff
@@ -40,7 +40,7 @@ defmodule Parzival.Gamification.Mission do
 
     belongs_to :difficulty, Difficulty
 
-    has_many :tasks, Task, on_replace: :delete_if_exists
+    has_many :tasks, Task
```
Comment (RuiL1904) [inline lib/parzival/gamification/mission.ex:43]: Undo this change. Otherwise, it would not be possible to see a mission's tasks Or even to see who completed them.

**Review by RuiL1904 — APPROVED** [review]
Great job! 🙌🏼
